config/routes.rb
Rails.application.routes.draw do
  resources :invites
  get 'test/new', as: :new_test
  get 'test/item/:id' => 'test#item', as: :test_item

  get 'sign_out' => 'application#signout', as: :sign_out

  resources :responses
  resources :participants

  devise_for :admins, controllers: {
    registrations: 'admins/registrations'
  }
  devise_for :examinators, controllers: {
    registrations: 'examinators/registrations'
  }

  get 'docs'=> 'application#docs'

  resources :itembanks

  root 'application#home'

end

app/models/invite.rb
class Invite < ActiveRecord::Base
  before_create :create_invite_hash!
  has_many :participants, foreign_key: :invite_hash, primary_key: :invite_hash
  belongs_to :examinator

  scope :by_examinator, ->(a) { where(examinator_id: a.id)}

  # Create invite hash, a hash that can be used to invite participants
  #
  # == Return:
  #   String that is unique
  def create_invite_hash!
    self.invite_hash = Digest::SHA2.new(256).update("#{self.serializable_hash}+#{Time.now}+jibffffrrrji!@#sh").to_s[2..12]
  end

  # Returns the examinator email address, if known
  #
  # @return [String] with email address or Nil
  def examinator_email
    examinator ? examinator.email : nil
  end

  class << self
    # Returns the results of all invites.
    #
    # @return [Workbook::Book] A {http://github.com/murb/workbook workbook} that can be saved to e.g. XLSX, CSV or XLS
    def to_workbook
      w = Workbook::Book.new([["Examinator","Invite Hash","Codering","Opmerking","Deelnemer","Antwoorden","Estimates","URL"]])
      self.all.each do |invite|
        invite.participants.each do | participant |
          w.sheet.table << [ invite.examinator_email, invite.invite_hash, invite.code, invite.comments, participant.participant_hash, participant.responses_as_text, participant.outcome_text ]
        end
      end
      w
    end
  end

end

app/controllers/invites_controller.rb
class InvitesController < ApplicationController
  before_action :set_invite, only: [:show, :edit, :update, :destroy]
  before_action :own_invite_only, only: [:show, :edit, :update, :destroy]
  before_action :require_admin_or_examinator!

  # GET /invites
  # GET /invites.json
  def index
    if current_examinator
      @invites = Invite.by_examinator(current_examinator)
    elsif current_admin
      @invites = Invite.all
    else
      @invites = []
    end

    respond_to do |format|
      format.xlsx {
        w = @invites.to_workbook
        send_data  w.stream_xlsx, :filename => "responses #{Time.now}.xlsx"
      }
      format.html {}
    end
  end

  # GET /invites/1
  # GET /invites/1.json
  def show

  end

  # GET /invites/new
  def new
    @invite = Invite.new
  end

  # GET /invites/1/edit
  def edit
  end

  # POST /invites
  # POST /invites.json
  def create
    myparams = invite_params
    myparams[:examinator_id] = current_examinator.id if current_examinator
    @invite = Invite.new(myparams)


    respond_to do |format|
      if @invite.save
        format.html { redirect_to @invite, notice: 'De uitnodiging is aangemaakt.' }
        format.json { render :show, status: :created, location: @invite }
      else
        format.html { render :new }
        format.json { render json: @invite.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /invites/1
  # PATCH/PUT /invites/1.json
  def update
    respond_to do |format|
      if @invite.update(invite_params)
        format.html { redirect_to @invite, notice: 'De uitnodiging is bijgewerkt.' }
        format.json { render :show, status: :ok, location: @invite }
      else
        format.html { render :edit }
        format.json { render json: @invite.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /invites/1
  # DELETE /invites/1.json
  def destroy
    @invite.destroy
    respond_to do |format|
      format.html { redirect_to invites_url, notice: 'De uitnodiging is verwijderd.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_invite
      @invite = Invite.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def invite_params
      params.require(:invite).permit(:comments, :code)
    end

    def own_invite_only
      @invite.examinator == current_examinator or current_admin
    end
end

app/helpers/invites_helper.rb
module InvitesHelper
end

app/views/invites/_form.html.erb
<%= simple_form_for(@invite) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :code %>
    <%= f.input :comments %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: :button %>
  </div>
<% end %>

app/views/invites/_invite_mail.html.erb
* Dit is een automatisch gegenereerd bericht *
----

U bent uitgenodigd om deel te nemen aan de vragenlijst kwaliteit van leven bij COPD. Volg de link hieronder:

<%= full_link %>

----

app/views/invites/edit.html.erb
<h1>Editing Invite</h1>

<%= render 'form' %>

<%= link_to 'Show', @invite %> |
<%= link_to 'Back', invites_path %>

app/views/invites/index.html.erb
<h1>Uitnodigingen &amp; deelnemers</h1>
<p>Om de resultaten van uw eigen deelnemers later gemakkelijk terug te vinden en hun gegevens in een keer te kunnen downloaden kunt u de deelnemer uitnodigen met een uniek voor deze toepassing gegenereerde sleutel.</p>
<p>U kunt ook achteraf een deelnemer koppelen door hem of haar te vragen de resultaten naar u door te sturen, als ingelogde afnemer kunt u een nog niet aan een afnemer gekoppelde deelnemer toevoegen aan uw deelnemers.</p>
<%= link_to 'Download de resultaten van deze patienten.', invites_path(format: :xlsx) %>
<table>
  <thead>
    <tr>
      <th>Sleutel</th>
      <th>Code</th>
      <th>Opmerkingen</th>
      <th>Examinator</th>
      <th>Deelnemers</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @invites.each do |invite| %>
      <tr>
        <td><%= invite.invite_hash %></td>
        <td><%= invite.code %></td>
        <td><%= invite.comments %></td>
        <td><%= invite.examinator_email %></td>
        <td><ul><% invite.participants.each do |participant| %><li><%= link_to participant.short_hash, participant, "data-no-turbolink" => true%></li><% end %></ul></td>
        <td><%= link_to new_participant_url(invite_hash: invite.invite_hash), new_participant_url(invite_hash: invite.invite_hash)%></td>
        <td><%= link_to 'Stel uitnodigingsmail op', "mailto:?body=#{url_encode(render(partial: 'invite_mail', locals: {full_link:new_participant_url(invite_hash: invite.invite_hash)}))}"%>
        <td><%= link_to 'Verwijder uitnodiging', invite, method: :delete, data: { confirm: 'Wanneer u een uitnodiging verwijderd en een deelnemer maakt toch gebruik van de uitnodiging verliest u de koppeling met uw genodigde deelnemer.' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Maak een nieuwe uitnodiging', new_invite_path %>

app/views/invites/new.html.erb
<h1>New Invite</h1>

<%= render 'form' %>

app/views/invites/show.html.erb
<p>De code is een vrij in te voeren, en niet verplicte code, die u wellicht wenst te gebruiken bij latere verwerking van de gegevens. In de opmerkingen kunt u vrije gegevens invullen. Wel wijzen we u er op dat u hier geen persoonsidentificerende gegevens kunt zetten, hiervoor is het beveiligingsniveau niet op het juiste niveau. Ook wanneer u een e-mail laat opstellen vanuit deze applicatie worden er géén deelnemeridentificerende gegevens opgeslagen.</p>

<p>
  <strong>Code:</strong>
  <%= @invite.code %>
</p>
<p>
  <strong>Opmerkingen:</strong>
  <%= @invite.comments %>
</p>

<p>
  <strong>Examinator:</strong>
  <%= @invite.examinator.email if @invite.examinator %>
</p>
<% if @invite.participants.count > 0%>
<h3>Deelnemers</h3>

<table>
<%= render @invite.participants %>
</table>
<p>Deze deelnemers zijn uitgenodigd met de volgende URL: </p>
<div class="panel"><p><%= new_participant_url({invite_hash: @invite.invite_hash}) %></p></div>

<% else %>
<p>U kunt een nieuwe deelnemer uitnodigen met de volgende URL zodat uw codering en aantekeningen gekoppeld blijven aan de deelnemer(s) (u kunt de URL hergebruiken voor meerdere deelnemers)</p>
<div class="panel"><p><%= new_participant_url({invite_hash: @invite.invite_hash}) %></p></div>
<% end %>

<%= link_to 'Edit', edit_invite_path(@invite) %> |
<%= link_to 'Back', invites_path %>