config/routes.rb
Rails.application.routes.draw do
  resources :invites
  get 'test/new', as: :new_test
  get 'test/item/:id' => 'test#item', as: :test_item

  get 'sign_out' => 'application#signout', as: :sign_out

  resources :responses
  resources :participants

  devise_for :admins, controllers: {
    registrations: 'admins/registrations'
  }
  devise_for :examinators, controllers: {
    registrations: 'examinators/registrations'
  }

  get 'docs'=> 'application#docs'

  resources :itembanks

  root 'application#home'

end

app/models/participant.rb
class Participant < ActiveRecord::Base
  before_create :hash_participant!
  has_many :responses
  validates :participant_hash, uniqueness: true
  validates :age, format: { with: /[0-9]*/ }
  validates_presence_of :age
  belongs_to :itembank
  belongs_to :invite, foreign_key: :invite_hash, primary_key: :invite_hash
  has_one :examinator, through: :invite

  # Returns a hash representing the participant('s session)
  #
  # @return [String] a hashed string
  def hash_participant!
    self.participant_hash = Digest::SHA2.new(256).update("#{self.serializable_hash}+#{Time.now}+jibrrrji!@#sh.+#{session}").to_s
  end

  # Parameterized ID
  #
  # @return [String] the participant_hash
  def to_param
    "#{participant_hash}"
  end

  # Short ID
  #
  # @return [String] the participant_hash shortened to 8 characters
  def short_hash
    to_param[0..7]
  end

  # Responses as text returns the participant's responses as text
  #
  # @return [String] with the responses in ASCII text
  def responses_as_text
    rv = ""
    responses.each do |r|
      rv << "[#{r.itembank_id},#{r.item_id}]=#{r.value}\n"
    end
    rv
  end


  # Outcome text returns the participant's outcome as text
  #
  # @return [String] with the outcome in ASCII text
  def outcome_text
    "Lichamelijk functioneren: #{evaluate[:estimate][0].round(1)} (#{evaluate[:se][0].round(1)})\nVermoeidheid: #{evaluate[:estimate][1].round(1)} (#{evaluate[:se][1].round(1)})\nVermogen om aandeel te hebben in sociale rollen en activiteiten: #{evaluate[:estimate][2].round(1)} (#{evaluate[:se][2].round(1)})\nImpact van COPD-gerelateerde klachten: #{evaluate[:estimate][3].round(1) }(#{evaluate[:se][3].round(1)})"
  end

  # Init response initializes a new response for the current participant
  #
  # @param response_params sets the new response's parameters
  # @return [Response] as an object

  def init_response response_params
    responses.where(item_id:response_params[:item_id]).destroy_all
    response = Response.new(response_params)
    response.participant = self
    response
  end

  # Evaluates all responses given and returns the outcomes, see Itembank#evaluate
  #
  # @return [Hash] see {Itembank#evaluate}
  def evaluate
    @evaluate ||= itembank.evaluate(responses_to_stat_hash,itembank.items.alphas.first.count.times.collect{1})
  end

  # Translate responses to an hash to be used in the {#evaluate} method
  #
  # @return [Hash] see {Response#evaluate}
  def responses_to_stat_hash
    responses.to_stat_hash(self)
  end
end

app/controllers/participants_controller.rb
class ParticipantsController < ApplicationController
  before_action :set_participant, only: [:show, :edit, :update, :destroy]
  before_action :require_admin_or_examinator!, only: [:index, :destroy, :edit, :update]


  # GET /participants
  # GET /participants.json
  def index
    @participants = Participant
    if current_admin
      @participants = @participants.all
    elsif current_examinator
      @participants = @participants.for_examinator(current_examinator)
    else
      @participants = []
    end
  end

  # GET /participants/1
  # GET /participants/1.json
  def show
    @title = "De score (#{@participant.short_hash})"
  end

  # GET /participants/new
  def new
    @title = "Start de deelname"
    session.destroy
    invite_hash = params[:invite_hash].to_s
    @participant = Participant.new(session: session.id, invite_hash: invite_hash)
  end

  # GET /participants/1/edit
  def edit
  end

  # POST /participants
  # POST /participants.json
  def create
    @participant = Participant.new(participant_params.merge({session: session.id, itembank_id: Itembank.first.id}))


    respond_to do |format|
      if @participant.save
        format.html { redirect_to new_test_path, notice: 'Uw gegevens zijn vastgelegd, begin de test!' }
        format.json { render :show, status: :created, location: @participant }
      else
        format.html { render :new }
        format.json { render json: @participant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /participants/1
  # PATCH/PUT /participants/1.json
  def update
    respond_to do |format|
      if @participant.update(participant_params)
        format.html { redirect_to @participant, notice: 'De deelnemer is bijgewerkt.' }
        format.json { render :show, status: :ok, location: @participant }
      else
        format.html { render :edit }
        format.json { render json: @participant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /participants/1
  # DELETE /participants/1.json
  def destroy
    @participant.destroy
    respond_to do |format|
      format.html { redirect_to participants_url, notice: 'De deelnemer is verwijderd.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_participant
      @participant = Participant.find_by_participant_hash(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def participant_params
      params.require(:participant).permit(:session, :invite_hash, :participant_hash, :age, :gender)
    end

    def require_admin_or_examinator!
      redirect_to root_path, notice: "U dient ingelogd te zijn als administrator of examinator van deze deelnemer." unless (current_admin or (current_examinator and (@participant.examinator == current_examinator or @participant.examinator.nil?)))
    end

end

app/helpers/participant_helper.rb
module ParticipantHelper
end

app/helpers/participants_helper.rb
module ParticipantsHelper
end

app/views/participants/_form.html.erb
<%= simple_form_for(@participant) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.hidden_field :invite_hash, type: :hidden %>
    <%= f.input :age %>
    <%= f.collection_radio_buttons( :gender, [['M','Man'], ['F','Vrouw']], :first, :last) %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, "Start de test", class: 'small button' %>
  </div>
<% end %>

app/views/participants/_participant.html.erb
<tr><td><%= link_to participant.invite_hash, participant%></td><td><%=participant.age%></td><td><%=participant.gender%></td><td></tr>

app/views/participants/edit.html.erb
<h1>Bewerk de deelnemer</h1>

<%= render 'form' %>

<%= link_to 'Terug', @participant %>

app/views/participants/index.html.erb
<h1>Listing Participants</h1>

<table>
  <thead>
    <tr>
      <th>Session</th>
      <th>Invite hash</th>
      <th>Participant hash</th>
      <th>Age</th>
      <th>Gender</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @participants.each do |participant| %>
      <tr>
        <td><%= participant.session %></td>
        <td><%= participant.invite_hash %></td>
        <td><%= participant.participant_hash %></td>
        <td><%= participant.age %></td>
        <td><%= participant.gender %></td>
        <td><%= link_to 'Show', participant %></td>
        <td><%= link_to 'Edit', edit_participant_path(participant) %></td>
        <td><%= link_to 'Destroy', participant, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Participant', new_participant_path %>

app/views/participants/new.html.erb
<div class="focusform">
  <h1>Uw gegevens</h1>

<%= render 'form' %>

</div>

app/views/participants/show.html.erb
<% if current_examinator or current_admin %>
<div class="right"><% if @participant.examinator.nil? and current_examinator %>
  <%= simple_form_for(@participant) do |f| %>

    <div class="form-inputs">
      <%= f.hidden_field :invite_hash, type: :hidden, value: Invite.create(examinator_id: current_examinator.id).invite_hash %>
    </div>

    <div class="form-actions">
      <%= f.button :submit, "Beschouw deze deelnemer als mijn genodigde", class: 'small button success' %>
    </div>
  <% end %>
<% end %>
</div>
<h1>Score rapport</h1>
<h3 class="subheader">Adaptieve kwaliteit van leven vragenlijst voor COPD</h3>
<p>Deze vragenlijst bestrijkt vier domeinen die te maken hebben met kwaliteit van leven: vermoeidheid, impact van COPD-gerelateerde klachten, lichamelijk functioneren, en vermogen om aandeel te hebben in sociale rollen en activiteiten.</p>
<p>De scores op deze vier domeinen zijn geschat op een schaal met een gemiddelde van 0 en een standaard deviatie van 1 (z-scores). Gemiddeld betekent hier: gemiddeld voor een COPD-patiënt.</p>
<p>Patiënt <%=@participant.short_hash%> had de volgende scores (standaard meetfout tussen haakjes) op deze vier domeinen: </p>
<ul>
  <li><%= @participant.evaluate[:estimate][0].round(1) %> (<%= @participant.evaluate[:se][0].round(1) %>) op lichamelijk functioneren</li>
  <li><%= @participant.evaluate[:estimate][1].round(1) %> (<%= @participant.evaluate[:se][1].round(1) %>) op vermoeidheid</li>
  <li><%= @participant.evaluate[:estimate][2].round(1) %> (<%= @participant.evaluate[:se][2].round(1) %>) op vermogen om aandeel te hebben in sociale rollen en activiteiten</li>
  <li><%= @participant.evaluate[:estimate][3].round(1) %> (<%= @participant.evaluate[:se][3].round(1) %>) op impact van COPD-gerelateerde klachten</li>
</ul>
<p>De scores zijn hieronder weergegeven in een figuur.</p>
<%= render partial: 'graph.svg'%>
<h4>Toelichting bij de figuur</h4>
<p>In de figuur ziet u op de x-as de vier domeinen, en op de y-as de z-score op deze domeinen. De scores zijn weergegeven met wiebertjes: hoe langer het wiebertje, hoe minder nauwkeurig de score geschat kon worden. Het kan voorkomen dat de schatting te onnauwkeurig is om serieus genomen te worden; in dat geval is er geen wit wiebertje afgebeeld voor het betreffende domein, maar een lange doorzichtige ovaal.</p>
<p>De lijn in het midden van de figuur geeft het gemiddelde weer; scores boven deze lijn zijn boven gemiddeld, en scores daaronder ondergemiddeld. De kleuren helpen u visueel bij het interpreteren: rood correspondeert met een relatief lage score, groen met een gemiddelde tot relatief hoge score. </p>

<h4>Toelichting interpretatie van de score</h4>
<p>Een hogere score betekent voor alle domeinen een betere kwaliteit van leven. Een relatief hoge score op het domein vermoeidheid betekent dus dat de patiënt relatief weinig vermoeidheidsklachten ervaart. Dit maakt het makkelijker om de figuur te interpreteren.</p>
<p>U kunt de z-score gebruiken om de scores van patiënten onderling te vergelijken, maar ook om de voortgang bij een specifieke patiënt in kaart te brengen.</p>

<a href="#" data-reveal-id="meerInformatie" class="button">Extra toelichting: normgroep, T-scores en schattingsprocedure</a>

<div id="meerInformatie" class="reveal-modal" data-reveal aria-labelledby="modalTitle" aria-hidden="true" role="dialog">
  <h2 id="modalTitle">Extra toelichting: normgroep, T-scores en schattingsprocedure</h2>
<h4>Normgroep en verdeling van scores</h4>
<p>Wij hebben de normering gebaseerd op een groep van 668 COPD-patiënten afkomstig uit heel Nederland, uit de eerste, tweede en derde lijn. Er zijn op dit moment geen aparte normen beschikbaar voor subgroepen (man/vrouw, GOLD stadium). De z-score verdelingen voor de vier domeinen zien er voor de normgroep als volgt uit:</p>

<%=image_tag 'density.full.multi.png', style: 'width: 100%'%>
<h5>Vergelijken van de domeinscores met scores op bestaande tests</h5>
<p>Zoals te zien is, zijn z-scores niet per definitie normaal verdeeld. De verdeling hangt af van de populatie/steekproef. Dit betekent ook dat een z-score op een test niet direct kan worden vergeleken met een z-score op een andere test. Om vergelijking mogelijk te maken, kan men gebruik maken van T-scores. Om van z-scores T-scores te maken wordt gebruik gemaakt van een zogenaamde normaliserende transformatie. T-scores zijn dus normaal verdeeld, met een gemiddelde van 50 en een standaard deviatie van 10. De T-scores van patiënt X zijn:</p>
<ul>
  <li><%= @participant.evaluate[:t_score][0].round(1) %> (<%= @participant.evaluate[:se][0].round(1) %>) op lichamelijk functioneren</li>
  <li><%= @participant.evaluate[:t_score][1].round(1) %> (<%= @participant.evaluate[:se][1].round(1) %>) op vermoeidheid</li>
  <li><%= @participant.evaluate[:t_score][2].round(1) %> (<%= @participant.evaluate[:se][2].round(1) %>) op vermogen om aandeel te hebben in sociale rollen en activiteiten</li>
  <li><%= @participant.evaluate[:t_score][3].round(1) %> (<%= @participant.evaluate[:se][3].round(1) %>) op impact van COPD-gerelateerde klachten</li>
</ul>

<h4>Toelichting schatting van scores
<p>De vragenlijst is op een adaptieve wijze afgenomen. Dit houdt in dat niet alle patiënten dezelfde vragen beantwoorden, maar alleen die vragen die voor hen relevant zijn. Die relevantie wordt gebaseerd op hun antwoordpatroon. Als een patiënt “heel erg” antwoord op een vraag, is de vervolgvraag een andere dan wanneer hij/zij “helemaal niet” zou antwoorden. </p>
<p>Op de achtergrond loopt een wiskundig algoritme mee, dat is gebaseerd op een statistisch model. Wij hebben gekozen om gebruik te maken van een multidimensioneel Item Respons Theorie (IRT) model: het Graded Response Model. Dit model relateert het antwoord wat door de patiënt wordt gegeven op een specifieke vraag aan een schatting van zijn/haar positie op de vier domeinen. We zijn uitgegaan van een zogenaamd “ simple structure” model, waarbij vragen zijn toegewezen aan een specifiek domein. De multidimensionaliteit zit hem in de correlaties tussen de domeinen: in dit IRT model is rekening gehouden met de samenhang tussen de vier domeinen, om zo de schattingen nog nauwkeuriger te maken. </p>
<p>De steekproef die is gebruikt voor de normering is ook gebruikt voor het schatten van de IRT parameters van de vragen. Deze worden gebruikt in het algoritme van de adaptieve test. Dit maakt het mogelijk om scores van patiënten te vergelijken, ook als ze niet dezelfde vragen hebben beantwoord.</p>
<p>Het IRT model is geschat met behulp van het mirt package in het software programma R, zo ook in het MIRT pakket ontwikkeld door Cees Glas (de pakketten leveren aanvullende resultaten op).</p>

<h4>Aanvullende informatie</h4>
<p>Deze CAT is tot stand gekomen in samenwerking met PROMIS Nederland, zie voor meer informatie <a href="http://www.dutchflemishpromis.nl">dutchflemishpromis.nl</a>.</p>

<p>Voor meer informatie over het berekenen en interpreteren van T-scores verwijzen we u naar de volgende boeken: </p>
<p>Spitz, J. C. (1971). <em>Statistiek voor Psychologen, Pedagogen, Sociologen.</em> Amsterdam/Brussel: Agon Elsevier.<br/>
Drenth, P. J. D., &amp; Sijtsma, K. (2006). <em>Testtheorie: Inleiding in de theorie van de psychologische test en zijn toepassingen</em> (4 ed.). Houten: Bohn Stafleu van Loghum.</p>

<p>Voor meer informatie over IRT en CAT verwijzen we u naar de volgende boeken:</p>
<p>Embretson, S. E., &amp; Reise, S. (2000). <em>Item response theory for psychologists</em>. Mahwah, NJ: Erlbaum.<br/>
Van der Linden, W. J., &amp; Glas, C. A. W. (Eds.). (2000). <em>Computerized Adaptive Testing: Theory and Practice</em>. Dordrecht: Kluwer Academic Publishers.<br/>
Veldkamp, B.P. &amp; van der Linden, W.J. (2002). <em>Multidimensional constrained adaptive testing</em>. Psychometrika, 67, 575-588.</p>

<p>Voor meer informatie over de selectie van de vier domeinen verwijzen we u naar de volgende artikelen:</p>
<p>Paap, M. C. S., Bode, C., Lenferink, L. I. M., Groen, L. C., Terwee, C. B., Ahmed, S., ... van der Palen, J. (2014). Identifying key domains of health-related quality of life for patients with Chronic Obstructive Pulmonary Disease: the patient perspective. <em>Health Qual Life Outcomes</em>, 12(1), 106.<br/>
Paap, M. C. S., Bode, C., Lenferink, L. I. M., Terwee, C. B., &amp; van der Palen, J. (2015). Identifying key domains of health-related quality of life for patients with chronic obstructive pulmonary disease: interviews with healthcare professionals. <em>Quality of Life Research</em>, 24(6), 1351-1367. </p>


  <a class="close-reveal-modal" aria-label="Close">&#215;</a>
</div>
<% else %>
<h1>Bedankt voor uw deelname.</h1>
<% if @participant.invite_hash? %>
<p>Uw behandelaar heeft uw scores ontvangen.</p>
<% else %>
<p>U dient deze pagina door te sturen naar uw behandelaar. Dit doet u door het adres (of koppeling) van deze pagina te kopiëren en te plakken in een e-mailbericht of de deelfunctionaliteit van uw browser te gebruiken.</p>
<p>Het adres (of koppeling) van deze pagina is:</p>
<pre><%=participant_url(@participant)%></pre>
<p>Bedankt voor uw medewerking.</p>
<% end %>


<% end %>

<div class="panel debug">

<p>
  <strong>Session:</strong>
  <%= @participant.session %>
  <em><%= (current_participant == @participant) ? "Huidige sessie!" : ""%></em>
</p>

<p><%= link_to "Antwoorden", responses_path(participant_hashes: @participant.participant_hash)%>

<p>
  <strong>Invite hash:</strong>
  <%= link_to @participant.invite_hash, @participant.invite %>
</p>

<p><strong>Result:</strong></p>
  <table>
    <body>
      <tr><th>Waardes</th>
  <% @participant.evaluate[:estimate].each do |v|  %>
      <td><%= v%></td>
  <% end %>
      </tr>
      <tr><th>Variantie</th>
  <% @participant.evaluate[:variance].each do |v|  %>
      <td><%= v%></td>
  <% end %>
      </tr>
          <tr><th>T-score</th>
      <% @participant.evaluate[:t_score].each do |v|  %>
          <td><%= v%></td>
      <% end %>
          </tr>
  </table>

<p>
  <strong>Age:</strong>
  <%= @participant.age %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @participant.gender %>
</p>
</div>




<%#= link_to 'Bewerk deze deelnemer', edit_participant_path(@participant) %>