config/routes.rb
Rails.application.routes.draw do
  resources :invites
  get 'test/new', as: :new_test
  get 'test/item/:id' => 'test#item', as: :test_item

  get 'sign_out' => 'application#signout', as: :sign_out

  resources :responses
  resources :participants

  devise_for :admins, controllers: {
    registrations: 'admins/registrations'
  }
  devise_for :examinators, controllers: {
    registrations: 'examinators/registrations'
  }

  get 'docs'=> 'application#docs'

  resources :itembanks

  root 'application#home'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= @title ? "#{@title} - " : ""%>Vragenlijst kwaliteit van leven bij COPD</title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <% if current_registered_user? %>
      <nav class="top-bar" data-topbar role="navigation">
        <ul class="title-area">
          <li class="name">
            <h1><a href="/">Kwaliteit van leven bij COPD</a></h1>
          </li>
           <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
          <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
        </ul>

        <section class="top-bar-section">
          <!-- Right Nav Section -->
          <ul class="right">
            <li class=""><%=link_to 'Uitloggen', sign_out_path %></li>

          </ul>

          <ul class="left">
            <% if current_admin %>
              <li class="<%='active' if controller.class==InvitesController%>"><%= link_to 'Genodigden', invites_path %></li>
              <!-- <li class="<%='active' if controller.class==ParticipantsController%>"><%= link_to 'Participants', participants_path %></li> -->
              <li class="<%='active' if controller.class==ItembanksController%>"><%= link_to 'Itembanks', itembanks_path %></li>
              <li class="<%='active' if controller.class==Examinators::RegistrationsController%>"><%= link_to 'Nieuwe examinator', new_examinator_registration_path %></li>
              <li class=""><%= link_to 'Documentatie', '/docs' %></li>
            <% end %>
            <% if current_examinator %>

              <li class="<%='active' if controller.class==InvitesController%>"><%= link_to 'Genodigden', invites_path %></li>
            <% end %>
          </ul>
        </section>
      </nav>
    <% else %>
      <nav class="top-bar" data-topbar role="navigation">
        <ul class="title-area">
          <li class="name">
            <h1><a href="/">Kwaliteit van leven bij COPD</a></h1>
          </li>
        </ul>
      </nav>
    <% end %>

    <div class="main">
    <% if notice %>
    <div data-alert class="alert-box notice success"><%= notice %><a href="#" class="close">&times;</a></div>
    <% end %>
    <% if alert %>
    <div data-alert class="alert-box alert"><%= alert %><a href="#" class="close">&times;</a></div>
    <% end %>
      <div class="row">
        <div class="large-12 columns">
           <%= yield %>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="large-12 columns"><small>
        <% unless current_examinator %><%= link_to 'Log in als examinator', new_examinator_session_path %><% end %><%unless current_admin or current_examinator%> | <% end%><% unless current_admin %><%= link_to 'Log in als administrator', new_admin_session_path %><% end %>
      </small>
      <%= image_tag "unitwentelongfonds.png", style: "width: 314px; height: 114px; margin-top: -1em; margin-bottom: 1em; float: right"%>

    </div>
    </div>
  </body>
</html>